console.log('Thank you for downloading cs-file-system!');
console.log('Please use this document as a manual for the cmd operations\n');
console.log('Command Line Interface:');
console.log('-------------------------------------------------------------');
console.log('FORMAT: node config.js --cmd command-name [command arguments]');
console.log('EXAMPLE: node config.js --cmd keys --key cache --value off');
console.log('');
console.log('COMMAND ("--cmd") ARGUMENT VALUES:');
console.log('[1]: keys: sets the value of a config variable');
console.log('[2]: mount: register external storage device');
console.log('[3]: link: generate / register symlink');
console.log('[4]: scripts: generate system scripts');
console.log('');
console.log('ARGUMENTS FOR AVILABLE COMMANDS:');
console.log('command-name: "keys"');
console.log('[1]: --key [name of json key]');
console.log('[2]: --value [value to store]');
console.log('command-name: "mount"');
console.log('[1]: --alias [display name]');
console.log('[2]: --uuid [uuid of storage device]');
console.log('command-name: "link"');
console.log('[1]: --alias [display name]');
console.log('[2]: --path [absolute path of folder]');
console.log('command-name: "scripts"');
console.log('[1]: --type [script group to generate]');
console.log('[!] NOTE: ONLY AVAILABLE VALUE IS "startup" (for now)');
console.log('-------------------------------------------------------------');
